# Generated by Django 4.1.4 on 2023-09-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="downloads/")),
            ],
            options={
                "verbose_name": "Processed File",
                "verbose_name_plural": "Processed File",
            },
        ),
        migrations.CreateModel(
            name="TG263Data",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Target_Type", models.CharField(max_length=255)),
                ("Major_Category", models.CharField(max_length=255)),
                ("Minor_Category", models.CharField(max_length=255)),
                ("Anatomic_Group", models.CharField(max_length=255)),
                ("TG263_Primary_Name", models.CharField(max_length=255, unique=True)),
                ("TG263_Reverse_Order_Name", models.CharField(max_length=255)),
                ("Description", models.CharField(max_length=255)),
                ("FMAID", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "TG263 Data",
                "verbose_name_plural": "TG263 Data",
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
            ],
            options={
                "verbose_name": "Uploaded File",
                "verbose_name_plural": "Uploaded File",
            },
        ),
        migrations.CreateModel(
            name="LabelMapping",
            fields=[
                ("label_id", models.AutoField(primary_key=True, serialize=False)),
                ("original_label", models.CharField(max_length=255)),
                ("TG263_label", models.CharField(blank=True, max_length=255)),
                (
                    "TG263_Primary_Name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.tg263data",
                        to_field="TG263_Primary_Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Label Mapping",
                "verbose_name_plural": "Label Mapping",
            },
        ),
    ]
